---
fixtures:
  repositories:
    augeas_core: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup.git
    firewalld: https://github.com/voxpupuli/puppet-firewalld.git
    simp_options: https://github.com/simp/pupmod-simp-simp_options.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
  symlinks:
    simp_firewalld: "#{source_dir}"
